### ISSUE TITLE
NEW_RELIC_ENABLED env var not respected

### ISSUE THREAD

**Issue by rittneje** [newrelic/newrelic-lambda-extension#215]
## Description

If we set NEW_RELIC_ENABLED=0, the Go agent won't report anything. However, the extension does not respect this env var. Consequently, it waits for telemetry that will never come, and ends up timing out 200 ms before actual timeout. (From AWS's perspective, the function was running the whole time and we get billed for it.)

https://github.com/newrelic/newrelic-lambda-extension/blob/a8461c8ce89bc2411cc5ae5dd7e06e206e3407bd/main.go#L269-L300

## Steps to Reproduce

See above.

## Expected Behavior

Extension should be a no-op if NEW_RELIC_ENABLED=0.

**Comment by chaudharysaket** [comment]
Hi @rittneje 
We have`NEW_RELIC_LAMBDA_EXTENSION_ENABLED` lambda environment variable to enable/disable extension, as defined [here](https://github.com/newrelic/newrelic-lambda-extension/blob/a8461c8ce89bc2411cc5ae5dd7e06e206e3407bd/config/config.go#L41C56-L41C90)

Currently, we see that different language agent is using a different env var to enable instrumentation, as mentioned [here](https://github.com/newrelic/go-agent/issues/106#issuecomment-561242701). 
env var for controlling whether the agent is enabled differs across agents:
Go: [NEW_RELIC_ENABLED](https://godoc.org/github.com/newrelic/go-agent/v3/newrelic#ConfigFromEnvironment)
Ruby: [NEW_RELIC_AGENT_ENABLED](https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration#general)
Node.js: [NEW_RELIC_ENABLED](https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#exports_config)

Since lambda extension supports all language runtimes, it should respect all agent specific env vars. We will look into the issue such that lambda extension should respect the agent enable environment variable. 
Thank you!

**Comment by rittneje** [comment]
@chaudharysaket Where was this fixed? I don't see any relevant commits, and there is no mention of NEW_RELIC_ENABLED in the source code.

**Comment by chaudharysaket** [comment]
Hi @rittneje
We can achieve similar results using the Extension specific environment variable `NEW_RELIC_LAMBDA_EXTENSION_ENABLED`. Since there are variations of `NEW_RELIC_ENABLED` env variable among different New Relic language agents, we thought of sticking to `NEW_RELIC_LAMBDA_EXTENSION_ENABLED` for Extension. Introducing new environment variables for different language agents would serve same purpose. 

Could you please help us understand cases where `NEW_RELIC_LAMBDA_EXTENSION_ENABLED` might not be a replacement for `NEW_RELIC_ENABLED`? 
Thank you

**Comment by rittneje** [comment]
@chaudharysaket As clearly mentioned in the issue description, the bug is that `NEW_RELIC_ENABLED=0` causes the agent not to log anything, which in turn causes the extension to block until the lambda timeout. It is required for the extension to abide by this environment variable in order to be compatible.

**Comment by chaudharysaket** [comment]
Okay. We will look into the issue shortly such that extension will abide by the `NEW_RELIC_ENABLED` env variable. Thank you!

**Comment by rittneje** [comment]
@chaudharysaket The other thing I will share is that `NEW_RELIC_LAMBDA_EXTENSION_ENABLED=0` on its own is still useful, since that allows us to force it to revert to the old "log group subscription" approach. So `NEW_RELIC_ENABLED=0` shouldn't be considered a replacement for it, it just takes priority.

**Comment by rittneje** [comment]
@chaudharysaket This issue needs to be reopened. You only considered “false” not “0”.
