### ISSUE TITLE
Function logs sometimes send in subsequent invocation

### ISSUE THREAD

**Issue by arnogeurts** [newrelic/newrelic-lambda-extension#42]
## Description

Because the main loop and the function log loop are running completely independently, it sometimes happens that Lambda runtime freezes before the function logs are sent to New Relic.

## Expected Behavior

Function logs are send within the same Lambda invocation as they are produced.

## Relevant Logs / Console output

<img width="1525" alt="Screenshot 2021-01-22 at 13 08 24" src="https://user-images.githubusercontent.com/1117484/105638574-8a54df00-5e73-11eb-9031-f1a89175f166.png">

These are the logs for a Lambda function that is invoked every 5 minutes. You can see from the 300000ms response time, that the logs are actually send in the subsequent Lambda invocation.

**Comment by kolanos** [comment]
cc'ing @MattWhelan

**Comment by MattWhelan** [comment]
Yes, this is by design. 

Function logs are batched by the platform, and delivered in batches. When the extension receives a batch, it sends it as quickly as possible, but it doesn't delay the call to the /next API. If the request fails, it gets retried. 

The tradeoff here is like this: either we can delay the /next call (which delays the function's response payload, and incurs billing charges), or we can not, and run the risk of timeouts and delays. For function logs, we've chosen not. 

A function that gets invoked once every five minutes is pretty much the worst case for our strategy. We hope for future platform improvements that change the tradeoff we have to make here, but for now, this is the best the extension can do.

Cloudwatch-based ingest may be a better fit for a function invoked so infrequently, for now.
